version: '3.8'

services:
  # ===== n8n Service =====
  n8n:
    build:
      context: .
      dockerfile: Dockerfile
    image: n8n-with-ffmpeg:latest
    container_name: n8n
    user: root
    restart: always
    ports:
      - "5678:5678"
    environment:
      - N8N_USER_FOLDER=/home/node
      - GENERIC_TIMEZONE=Asia/Ho_Chi_Minh
      - WEBHOOK_URL=https://n8n.thetaphoa.store/
      - N8N_PROTOCOL=https
      - N8N_HOST=n8n.thetaphoa.store
      - N8N_PROXY_HOPS=1
      - N8N_SKIP_WEBHOOK_AUTHENTICATION=true
      - N8N_RUNNERS_ENABLED=true
      - N8N_DISABLE_PRODUCTION_MAIN_PROCESS=true
      - N8N_SKIP_WEBHOOK_DEREGISTRATION_SHUTDOWN=true
      - NODES_EXCLUDE=[]
      - N8N_RESTRICT_FILE_ACCESS_TO=/files/
    volumes:
      - n8n_data:/home/node/.n8n
      - ./local-files:/files #maps a folder for local files
    networks:
      - n8n_network

networks:
  n8n_network:
    driver: bridge

volumes:
  n8n_data:
    external: true
    name: n8n_data